version: '1.1.0.{build}'

image:
- Ubuntu

platform:
  - x64
  
configuration:
- Release

install:
  - sh: sudo ./esp/setup.sh

build_script:
  - cd ~/esp-idf
  - . ./export.sh
  - cd ~
  - idf.py build