version: '1.1.0.{build}'

image:
- Ubuntu

platform:
  - x64
  
configuration:
- Release

install:
  - wget https://www.python.org/ftp/python/3.7.15/Python-3.7.15.tgz
  - tar -xvf Python-3.7.15.tgz > /dev/null
  - cd Python-3.7.15
  - sudo ./configure > /dev/null
  - sudo make > /dev/null
  - sudo make install > /dev/null
  - cd ~
  - sudo apt-get install -y git wget flex bison gperf python3 python3-venv ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
  - git clone https://github.com/Kitware/CMake.git > /dev/null
  - cd CMake
  - sudo ./bootstrap  > /dev/null
  - sudo make  > /dev/null
  - sudo make install  > /dev/null
  - cd ~
  - git clone --recursive https://github.com/espressif/esp-idf.git > /dev/null
  - cd esp-idf
  - sudo ./install.sh esp32 > /dev/null

build_script:
  - . ~/esp-idf/export.sh
  - cd /home/appveyor/projects/simpleson-esp
  - idf.py build