version: '1.1.0.{build}'

image:
- Ubuntu

platform:
  - x64
  
configuration:
- Release

install:
  - wget https://www.python.org/ftp/python/3.7.15/Python-3.7.15.tgz
  - tar -xvf Python-3.7.15.tgz
  - cd Python-3.7.15
  - sudo ./configure
  - sudo make
  - sudo make install
  - cd esp
  - sudo ./setup.sh

build_script:
  - cd esp/esp-idf
  - . ./export.sh
  - cd ../../
  - idf.py build